import { CardData, RuneData, ArtefactData, StructureData, CardType, StructureType, ElementType, CastTier, TargetType, DEFAULT_CAST_CONFIG } from './types';

export const ELEMENT_THEMES = {
  [ElementType.FIRE]: {
    bg: '#0f0505', 
    border: 'linear-gradient(135deg, #7f1d1d 0%, #ef4444 50%, #450a0a 100%)',
    accent: '#ef4444',
    text: '#fecaca',
    secondaryText: '#991b1b',
    glow: 'rgba(239, 68, 68, 0.4)',
    overlay: 'linear-gradient(to bottom, rgba(69, 10, 10, 0.8), rgba(0,0,0,0.9))'
  },
  [ElementType.WATER]: {
    bg: '#020617',
    border: 'linear-gradient(135deg, #1e3a8a 0%, #38bdf8 50%, #0f172a 100%)',
    accent: '#38bdf8',
    text: '#e0f2fe',
    secondaryText: '#075985',
    glow: 'rgba(56, 189, 248, 0.4)',
    overlay: 'linear-gradient(to bottom, rgba(15, 23, 42, 0.8), rgba(0,0,0,0.9))'
  },
  [ElementType.EARTH]: {
    bg: '#1a120b',
    border: 'linear-gradient(135deg, #3f2e26 0%, #65a30d 50%, #1a120b 100%)',
    accent: '#84cc16',
    text: '#ecfccb',
    secondaryText: '#365314',
    glow: 'rgba(132, 204, 22, 0.4)',
    overlay: 'linear-gradient(to bottom, rgba(39, 28, 25, 0.8), rgba(0,0,0,0.9))'
  },
  [ElementType.WIND]: {
    bg: '#111827',
    border: 'linear-gradient(135deg, #374151 0%, #2dd4bf 50%, #1f2937 100%)',
    accent: '#2dd4bf',
    text: '#ccfbf1',
    secondaryText: '#115e59',
    glow: 'rgba(45, 212, 191, 0.4)',
    overlay: 'linear-gradient(to bottom, rgba(17, 24, 39, 0.8), rgba(0,0,0,0.9))'
  },
  [ElementType.DARK]: {
    bg: '#0a0a0a',
    border: 'linear-gradient(135deg, #2e1065 0%, #000000 50%, #4c1d95 100%)',
    accent: '#7e22ce',
    text: '#f3e8ff',
    secondaryText: '#3b0764',
    glow: 'rgba(126, 34, 206, 0.4)',
    overlay: 'linear-gradient(to bottom, rgba(20, 5, 30, 0.8), rgba(0,0,0,0.9))'
  },
  [ElementType.ANCESTRAL]: {
    bg: '#022c22',
    border: 'linear-gradient(135deg, #134e4a 0%, #2dd4bf 40%, #115e59 100%)',
    accent: '#5eead4',
    text: '#ccfbf1',
    secondaryText: '#0f766e',
    glow: 'rgba(94, 234, 212, 0.5)',
    overlay: 'linear-gradient(to bottom, rgba(10, 40, 35, 0.8), rgba(0,0,0,0.9))'
  },
  [ElementType.TECNO]: {
    bg: '#18181b',
    border: 'linear-gradient(135deg, #22c55e 0%, #eab308 50%, #ef4444 100%)', // Glitchy RGB look
    accent: '#00ff9d',
    text: '#ecfccb',
    secondaryText: '#3f6212',
    glow: 'rgba(0, 255, 157, 0.4)',
    overlay: 'linear-gradient(to bottom, rgba(24, 24, 27, 0.9), rgba(0, 255, 157, 0.1))',
  },
  [ElementType.DIVINE]: {
    bg: '#2a2208',
    border: 'linear-gradient(135deg, #ca8a04 0%, #fef08a 50%, #854d0e 100%)',
    accent: '#facc15',
    text: '#fefce8',
    secondaryText: '#a16207',
    glow: 'rgba(250, 204, 21, 0.5)',
    overlay: 'linear-gradient(to bottom, rgba(42, 34, 8, 0.8), rgba(0,0,0,0.9))'
  }
};

export const RUNE_THEME = {
  bg: '#0f0518',
  border: 'linear-gradient(135deg, #2e1065 0%, #3b82f6 50%, #4c1d95 100%)',
  accent: '#a855f7',
  text: '#e9d5ff',
  glow: 'rgba(168, 85, 247, 0.5)',
};

export const ARTEFACT_THEME = {
  bg: '#1c1004',
  border: 'linear-gradient(135deg, #451a03 0%, #d97706 50%, #78350f 100%)',
  accent: '#f59e0b',
  text: '#fef3c7',
  glow: 'rgba(245, 158, 11, 0.5)',
};

export const STRUCTURE_THEME = {
  bg: '#0c1210',
  border: 'linear-gradient(135deg, #134e4a 0%, #2dd4bf 50%, #0f172a 100%)',
  accent: '#14b8a6',
  text: '#ccfbf1',
  secondaryText: '#0f766e',
  glow: 'rgba(20, 184, 166, 0.5)',
};

export const INITIAL_CARD: CardData = {
  id: 'new-card',
  name: 'Bola de Fogo',
  type: CardType.MAGIC,
  element: ElementType.FIRE,
  manaCost: 3,
  cooldown: 2,
  range: 4,
  baseDescription: 'Concentre a energia primordial em uma esfera instável que detona ao contato.',
  imageUrl: 'https://picsum.photos/400/500',
  imageOpacity: 60,
  contentOpacity: 85,
  noBackground: false,
  isCounter: false,
  castWeak: {
    ...DEFAULT_CAST_CONFIG,
    description: 'A esfera oscila e se dissipa parcialmente.',
    damage: 2,
    targets: [TargetType.OPPONENT],
  },
  castGood: {
    ...DEFAULT_CAST_CONFIG,
    description: 'Impacto direto causando queimaduras severas.',
    damage: 4,
    targets: [TargetType.OPPONENT],
    effects: [{ id: '1', name: 'Burn', level: 1, chips: 2 }]
  },
  castPerfect: {
    ...DEFAULT_CAST_CONFIG,
    description: 'Cataclismo localizado. A área é envolta em chamas eternas.',
    damage: 6,
    targets: [TargetType.OPPONENT, TargetType.FIELD],
    effects: [{ id: '2', name: 'Burn', level: 2, chips: 3 }]
  },
};

export const INITIAL_RUNE: RuneData = {
  id: 'new-rune',
  name: 'Runa Ancestral',
  activationEffect: 'Ao ser ativada, restaura 3 pontos de mana instantaneamente.',
  continuousEffect: 'Enquanto equipada, todas as magias de Fogo causam +1 de dano.',
  imageUrl: 'https://picsum.photos/400/500?grayscale',
  imageOpacity: 50,
  noBackground: false,
};

export const INITIAL_ARTEFACT: ArtefactData = {
  id: 'new-artefact',
  name: 'Cálice do Vazio',
  effect: 'Permite trocar a posição de dois aliados no tabuleiro, ignorando obstáculos.',
  cooldown: 3,
  imageUrl: 'https://picsum.photos/400/500?blur',
  imageOpacity: 70,
  noBackground: false,
};

export const INITIAL_STRUCTURE: StructureData = {
  id: 'new-structure',
  name: 'Muralha de Espinhos',
  type: StructureType.BARRIER,
  element: ElementType.EARTH,
  manaCost: 4,
  cooldown: 3,
  description: 'Uma barreira impenetrável que fere quem ousa tocá-la.',
  durability: 20,
  resistanceElement: ElementType.EARTH,
  resistanceLevel: 5,
  touchEffectElement: ElementType.EARTH,
  touchEffectValue: 2,
  continuousEffect: 'Bloqueia movimento de unidades não-voadoras.',
  imageUrl: 'https://picsum.photos/400/500?grayscale',
  imageOpacity: 60,
  noBackground: false,
  isCounter: false, // Updated default to false
};

export const TRANSLATIONS = {
  'pt-BR': {
    menu: {
      title: 'Wizards Ones Studio',
      subtitle: 'Selecione a ferramenta de criação',
      powerCard: 'Power Card',
      powerCardDesc: 'Crie Magias, Encantamentos e Selos.',
      rune: 'Rune',
      runeDesc: 'Forje runas antigas de poder.',
      artefact: 'Artefato',
      artefactDesc: 'Crie relíquias e itens lendários.',
      structure: 'Estrutura',
      structureDesc: 'Altares, Barreiras e Construções de Campo.',
      sanctuary: 'Santuário',
      sanctuaryDesc: 'Áreas sagradas de influência global.',
      imageCropper: 'Cortador de Imagens',
      imageCropperDesc: 'Ajuste e corte imagens para usar em seus cards.',
      back: 'Voltar ao Menu',
      underConstruction: 'Em Breve'
    },
    ui: {
      editorTitle: 'Editor',
      editorSubtitle: 'Configure os atributos do item.',
      general: 'Geral',
      cardName: 'Nome',
      type: 'Tipo',
      element: 'Elemento',
      manaCost: 'Custo Mana',
      cooldown: 'Cooldown',
      range: 'Alcance',
      art: 'Arte',
      upload: 'Upload do Dispositivo',
      fade: 'Fade da Imagem',
      contentFade: 'Fundo do Texto',
      descBase: 'Descrição Base',
      castConfig: 'Configuração de Cast (Dado)',
      damage: 'Dano',
      duration: 'Duração (Turnos)',
      descEffect: 'Descrição do Efeito',
      statusEffects: 'Status & Efeitos',
      targets: 'Alvos',
      add: 'Add',
      name: 'Nome',
      level: 'Nível',
      chips: 'Fichas',
      weak: 'Fraco',
      good: 'Moderado',
      perfect: 'Perfeito',
      activationEffect: 'Efeito de Ativação',
      continuousEffect: 'Efeito Contínuo',
      effect: 'Efeito',
      durability: 'Durabilidade',
      resistance: 'Resistência',
      runicElement: 'Elemento Rúnico',
      touchEffect: 'Dano por Contato',
      cropperTitle: 'Estúdio de Corte',
      dragToCrop: 'Arraste o retângulo para selecionar a área.',
      uploadImage: 'Carregar Imagem',
      downloadCrop: 'Baixar Recorte',
      zoom: 'Zoom / Tamanho',
      noBackground: 'Sem Fundo',
      edit: 'Editar',
      view: 'Visualizar',
      isCounter: 'É Counter?',
    },
    card: {
      [CardType.MAGIC]: 'Magia',
      [CardType.ENCHANTMENT]: 'Encantamento',
      [CardType.SEAL]: 'Selo',
      [CardType.BARRIER]: 'Barreira',
      [StructureType.ALTAR]: 'Altar',
      [ElementType.FIRE]: 'Fogo',
      [ElementType.WATER]: 'Água',
      [ElementType.EARTH]: 'Terra',
      [ElementType.WIND]: 'Vento',
      [ElementType.DARK]: 'Trevas',
      [ElementType.ANCESTRAL]: 'Ancestral',
      [ElementType.TECNO]: 'Tecno',
      [ElementType.DIVINE]: 'Divino',
      [CastTier.WEAK]: 'Fraco',
      [CastTier.GOOD]: 'Moderado',
      [CastTier.PERFECT]: 'Perfeito',
      [TargetType.PLAYER]: 'Jogador',
      [TargetType.FIELD]: 'Campo',
      [TargetType.OPPONENT]: 'Oponente',
      cooldown: 'RECARGA',
      range: 'ALCANCE',
    }
  },
  'en-US': {
    menu: {
      title: 'Wizards Ones Studio',
      subtitle: 'Select creation tool',
      powerCard: 'Power Card',
      powerCardDesc: 'Create Magics, Enchantments and Seals.',
      rune: 'Rune',
      runeDesc: 'Forge ancient runes of power.',
      artefact: 'Artefact',
      artefactDesc: 'Create relics and legendary items.',
      structure: 'Structure',
      structureDesc: 'Altars, Barriers and Field Constructions.',
      sanctuary: 'Sanctuary',
      sanctuaryDesc: 'Sacred areas of global influence.',
      imageCropper: 'Image Cropper',
      imageCropperDesc: 'Adjust and crop images for your cards.',
      back: 'Back to Menu',
      underConstruction: 'Coming Soon'
    },
    ui: {
      editorTitle: 'Editor',
      editorSubtitle: 'Configure item attributes.',
      general: 'Geral',
      cardName: 'Name',
      type: 'Type',
      element: 'Element',
      manaCost: 'Mana Cost',
      cooldown: 'Cooldown',
      range: 'Range',
      art: 'Art',
      upload: 'Upload Device',
      fade: 'Image Fade',
      contentFade: 'Text Background',
      descBase: 'Base Description',
      castConfig: 'Cast Configuration (Die)',
      damage: 'Damage',
      duration: 'Duration (Turns)',
      descEffect: 'Effect Description',
      statusEffects: 'Status & Effects',
      targets: 'Targets',
      add: 'Add',
      name: 'Name',
      level: 'Level',
      chips: 'Chips',
      weak: 'Weak',
      good: 'Good',
      perfect: 'Perfect',
      activationEffect: 'Activation Effect',
      continuousEffect: 'Continuous Effect',
      effect: 'Effect',
      durability: 'Durability',
      resistance: 'Resistance',
      runicElement: 'Runic Element',
      touchEffect: 'Contact Damage',
      cropperTitle: 'Crop Studio',
      dragToCrop: 'Drag the rectangle to select the area.',
      uploadImage: 'Upload Image',
      downloadCrop: 'Download Crop',
      zoom: 'Zoom / Size',
      noBackground: 'No Background',
      edit: 'Edit',
      view: 'View',
      isCounter: 'Is Counter?',
    },
    card: {
      [CardType.MAGIC]: 'Magic',
      [CardType.ENCHANTMENT]: 'Enchantment',
      [CardType.SEAL]: 'Selo',
      [CardType.BARRIER]: 'Barrier',
      [StructureType.ALTAR]: 'Altar',
      [ElementType.FIRE]: 'Fire',
      [ElementType.WATER]: 'Water',
      [ElementType.EARTH]: 'Earth',
      [ElementType.WIND]: 'Wind',
      [ElementType.DARK]: 'Dark',
      [ElementType.ANCESTRAL]: 'Ancestral',
      [ElementType.TECNO]: 'Tecno',
      [ElementType.DIVINE]: 'Divine',
      [CastTier.WEAK]: 'Weak',
      [CastTier.GOOD]: 'Moderate',
      [CastTier.PERFECT]: 'Perfect',
      [TargetType.PLAYER]: 'Player',
      [TargetType.FIELD]: 'Field',
      [TargetType.OPPONENT]: 'Opponent',
      cooldown: 'COOLDOWN',
      range: 'RANGE',
    }
  }
};